version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fsx-lustre"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dp766hl6kryh"
s3_prefix = "fsx-lustre"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Subnets=\"subnet-ac32d8d1\" SecurityGroups=\"sg-02632776\" NotificationEmail=\"croccale@amazon.com\""
image_repositories = []
